### PR TITLE
Sloves Tab Override

### PR DESCRIPTION
**Pull request by redmangospros**
Fixes Tab Overide In Scratch-Gui In A Issue By @dalearn With A Pull Request Made by @dalearn.
This PR, Fixes The Tab Overide coming down and fixes the tabs.

@mewtaylor I Think you need this from @dalearn Right?

### CODE REVIEW

**Comment by redmangospros** [comment]
Opps

**Comment by dalearn** [comment]
I'm confused as to what this did.  I am somewhat new to contributing to projects that aren't my own on Github and am trying to understand everything.  Can you explain please?

**Comment by redmangospros** [comment]
YYou Made this..

**Comment by dalearn** [comment]
But what happened to it?  has it been added to the source code or do I need to continue pursuing this?

**Comment by redmangospros** [comment]
No, It Has To Be Merged By A Owner, And What Was the purpose of thuis?

**Comment by dalearn** [comment]
The purpose of the PR was to do just as the description says and adds a small line to the bottom of each tab which makes it looks cleaner when tabs are selected.

**Comment by redmangospros** [comment]
Good, Now You Made A Issue On it, I will reopen it, so a St Member can check it.

**Comment by redmangospros** [comment]
Yay, I Made  Commit.

**Pull request merged**
