### PR TITLE
Design Changes

### PR DESCRIPTION
**Pull request by CosmicWebServices**
### Resolves

Resolves https://github.com/LLK/scratch-gui/issues/42 and some design features in https://github.com/LLK/scratch-gui/issues/1

### Proposed Changes

Before:
screenshot 2017-01-23 at 8 46 21 pm

After:
screenshot 2017-01-23 at 8 45 38 pm

### Reason for Changes

Two steps forward in design.

### CODE REVIEW

**Comment by thisandagain** [comment]
Thanks @CosmicWebServices. In the future please ask prior to opening a PR on issues that do not the "help wanted" label. I'll let @lifeinchords decide if he'd like to land this or not.

**Comment by CosmicWebServices** [comment]
@thisandagain OK I will keep that in mind :D

**Comment by TheBrokenRail** [comment]
Can you make the categories selector in the workspace the same color as the top area, It would fit in more and look more unified?

**Comment by CosmicWebServices** [comment]
@TheBrokenRail I just followed the design ideas

**Comment by lifeinchords** [comment]
Thanks for submitting this update @CosmicWebServices, and for your feedback @TheBrokenRail. I'm merging it in now, and we might see a bit of refactoring as the design evolves over the next few weeks.

**Comment by CosmicWebServices** [comment]
:D

**Pull request merged**
