### PR TITLE
fix(UI): fix cursor property when hovering account nav items

### LINKED ISSUE #4584: Cursor could turn into a hand when hovering account dropdown
### Expected Behavior

I think cursor should keeps same format when hovering any nav dropdown
like this:
img_0446

### Actual Behavior

But when you hovering account dropdown, cursor is this:
img_0457

and this:
img_0447

### Steps to Reproduce

1. Login
2. open account dropdown
3. hovering over menu item

### Operating System and Browser

MacOS Chrome

### PR DESCRIPTION
**Pull request by JinXJinX**
### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #4584 

### Proposed Changes

Change cursor to a hand when hovering account nav items

### Reason for Changes

make the UI look better and consistent

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [x] Chrome 
 * [x] Firefox 
 * [x] Safari
 
Windows
 * [x] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [x] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by towerofnix** [comment]
This is not the appropriate fix here, because the root of the problem is that the elements are not `<a>`s when they should be. That causes a problem arguably worse than the cursor being wrong - the elements do not actually behave like links. I've filed that in #4241, which is also labelled help wanted. Fixing that (by making the links `<a>`s) would both make them behave as links middle-click-wise as well as make `cursor: pointer` happen automatically (since that's the default browser style for `<a>`s).

**Comment by JinXJinX** [comment]
> This is not the appropriate fix here, because the root of the problem is that the elements are not `<a>`s when they should be. That causes a problem arguably worse than the cursor being wrong - the elements do not actually behave like links. I've filed that in #4241, which is also labelled help wanted. Fixing that (by making the links `<a>`s) would both make them behave as links middle-click-wise as well as make `cursor: pointer` happen automatically (since that's the default browser style for `<a>`s).

@towerofnix  Thanks for the advice. I agree that use < a> tag can solve both #4589 and #4241, and it will also reduce code complexity by remove the MenuItemContainer component. 

However, on the other hand, I'm not sure about the usage scenario of middle/ctrl/cmd-click account dropdown. Because only the user who read the scratch-gui source code, knows some buttons are links, others are not. for the most of users, they are all menu items. 

Therefore, If we add that implicit method. Does this make users confused? menu items' inconsistent behavior

**Comment by joker314** [comment]
HTML is supposed to describe a document. It should not be the website's decision how a website should be navigated, instead it should leave that to the customisable browser.

The advantages of using an `<a>` tag for links are:
- Many screen readers have an option to list all the links on a page.
- Many screen readers will tell you if an element is a clickable link (and this _is_ a link, and not just a button, especially because it's taking you to another page)
- Browser extensions can target links specifically
- Search Engine Optimisation
- Some people disable CSS, or override it, and they should still have obvious clues that they are dealing with clickable elements
- etc.

**Comment by JinXJinX** [comment]
@joker314 for example, those three dropdown don't contain any link
screen shot 2019-02-25 at 10 24 50 pm

**Comment by benjiwheeler** [comment]
About using `<a>` tags -- one of the tricky things is that some menu items (profile, my stuff, etc.) are links that will take you to another page, while others (undo, turbo, save, download, upload, etc.) are triggers for actions within the page. Even the menu items that will navigate the user away from the page often first do things like trigger an auto-save. It's not totally clear to me what the middle click (or command-click on Mac) behavior should be, or how to implement it.

**Comment by benjiwheeler** [comment]
I'm going to merge this PR because it's an improvement on where we are, even if it doesn't solve the problem on a deeper level. Thanks for the submission, @JinXJinX !

**Pull request merged**
