### PR TITLE
update node version on circle

### PR DESCRIPTION
**Pull request by picklesrus**
### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #

### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by apple502j** [comment]
Should resolve #5828

**Comment by picklesrus** [comment]
> Should resolve #5828

I was hoping it would, but it didn't :-/ Will spend some more time digging into this today.

**Comment by apple502j** [comment]
@picklesrus try bumping chromedriver?

**Comment by picklesrus** [comment]
There definitely seems to be a chromedriver version problem. Currently looks like Circle is using 80, but reporting a mismatch
```
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 80
      (Driver info: chromedriver=80.0.3987.16
```
I'll have to dig into where Circle is getting its version from. I don't really understand circle's config yet :)

**Comment by apple502j** [comment]
@picklesrus  I think this is how it works:
1) `circleci/node:10-browsers` always gives the latest version of Chrome, except: 
2) When the Node is EOL, it will no longer be updated (Node 8's EOL was 2019/12/31 so the latest version at that time was Chrome 79, but chromedriver was version 80, so it errored)

**Comment by picklesrus** [comment]
Done in other PRs a while back. Closing.

**Pull request closed without merging**
