### PR TITLE
Disable record button before mic access is given

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_
Fixes https://github.com/LLK/scratch-gui/issues/503

### Proposed Changes

_Describe what this Pull Request does_
Disable the record button (and gray it out) before mic access is given.

### Reason for Changes

_Explain why these changes should be made_
It should not be possible to start the recording before mic access is given. This doesn't really address the design problem mentioned in that issue, let's make a separate issue for that. 

@carljbowman thoughts? this is what it looks like

screen shot 2017-07-06 at 10 55 48 am
screen shot 2017-07-06 at 10 55 54 am

Note: the button is actually disabled, it cannot be clicked.

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
You should also change the text "Begin recording by clicking the button bellow" to something like "We need permission to use your mic"

**Comment by paulkaplan** [comment]
@carljbowman @CosmicWebServices what about something like this?

screen shot 2017-07-06 at 1 18 34 pm

**Comment by paulkaplan** [comment]
@ericrosenbaum thanks. Fixed by making sure that no callbacks are called after the audio recorder is disposed of.

**Comment by CosmicWebServices** [comment]
@paulkaplan Nice but also I do not think all browsers have a dialog in that area...

**Comment by paulkaplan** [comment]
@CosmicWebServices yeah, i think we'll have to deal with this more completely later in that linked issue. There is also the case where you deny mic access accidentally and then you need to click on some other button in the top right to give it (which we do not handle correctly right now).

**Pull request merged**
