### PR TITLE
fix: when input of import csv cancel,the input element should be hidden

### PR DESCRIPTION
**Pull request by Aaron-jo**
### Resolves

- when input of import csv cancel,the input element should be hidden

### Reason for Changes
When importing a .csv file to a list, user presses cancel button of browser prompt. This will result in Input Element not being removed

image

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [x] Chrome 
 * [ ] Firefox 
 * [ ] Safari

Windows
 * [x] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by chrisgarrity** [comment]
See the [contributor guidelines](https://github.com/LLK/.github/blob/main/CONTRIBUTING.md). We only accept PRs for issues that have been filed and been prioritized. Please file an issue with the steps to reproduce the problem so that it can be prioritized.

**Comment by Aaron-jo** [comment]
> See the [contributor guidelines](https://github.com/LLK/.github/blob/main/CONTRIBUTING.md). We only accept PRs for issues that have been filed and been prioritized. Please file an issue with the steps to reproduce the problem so that it can be prioritized.



> See the [contributor guidelines](https://github.com/LLK/.github/blob/main/CONTRIBUTING.md). We only accept PRs for issues that have been filed and been prioritized. Please file an issue with the steps to reproduce the problem so that it can be prioritized.

ok, i have already filed an [issue](https://github.com/LLK/scratch-gui/issues/7960#issue-1101492982), what should i do next?

**Comment by apple502j** [comment]
@chrisgarrity I believe the issue is already prioritized and marked as Help Wanted. #4681

**Comment by DNin01** [comment]
<sub>Hi! Just stumbled across this while searching to see if this was an existing issue.</sub>

I think the team closed your PR because they didn't realize this was resolving an existing issue. I think you can make a new PR if you want, and make sure to mention the original issue by adding `Resolves #4681` to your PR description.

**Pull request closed without merging**
