### PR TITLE
Allow really big projects to load all the time

### LINKED ISSUE #5844: Projects with many assets don't load in Chrome some of the time
### Expected Behavior

All projects load normally.

### Actual Behavior

A few projects have come to our attention that don't load in chrome, instead giving a blue error screen (BSOD).  These projects have tons of assets (hundreds).

https://scratch.mit.edu/projects/371197630/
https://scratch.mit.edu/projects/399970272/

If you look in the network tab as the project loads you will see that many assets load.  After loading a number of them, they start coming back as failed requests.  This seems to only happen when using Chrome.

The assets that fail to load can be loaded directly from the api.  

Reloading the page seems to work. The project is viewable.

The current theory is that this is a chrome bug which can only load a certain number of assets per page.  It seems that the first time you load it, the browser caches the responses for the images it finds, then only has to load the images it failed to load the first time, so it works the second time.

### Steps to Reproduce

Load one of the two projects listed above in chrome.
Note: you get a BSOD
reload the page
Note: the project loads this time.  It may take multiple reloads.

Load the project in another browser
Note: the project loads.

### Operating System and Browser

Mac Chrome

### PR DESCRIPTION
**Pull request by Chaos-emerald**
### Resolves

- Resolves #5844 

### Proposed Changes

Helps projects with many assets load in Chrome all the time.

### Reason for Changes

So large projects can always run in Chrome.

### CODE REVIEW

**Comment by Chaos-emerald** [comment]
@GarboMuffin, don't review this, it's in draft state.

**Comment by FunctionalMetatable** [comment]
@Chaos-emerald looks like this is in the wrong repo - make your pr on https://github.com/TurboWarp/scratch-gui please.

**Comment by GrahamSH-LLK** [comment]
This entire PR should be closed. Turbowarp is completely seperate, and should not be merged into scratch-gui. cc @BryceLTaylor

**Comment by BryceLTaylor** [comment]
Thanks for contributing to scratch!  In general, we only consider pull requests that only implement the changes described in them.  This one makes many many changes.  We recommend keeping PRs small so individual changes can be evaluated independently. 

If you'd like to make changes to Scratch-gui you should fork the original scratch-gui project and keep it up to date with llk/develop.  Turbowarp has separated far enough from Scratch-gui that we do not accept PRs directly from it.  

For more information, check out [our contributing guidelines](https://github.com/LLK/scratch-gui/blob/f03edcc9a018d8700b0145b3b496b3170b905162/.github/CONTRIBUTING.md).

**Pull request closed without merging**
