### PR TITLE
Fix input css to apply only to text fields

### PR DESCRIPTION
**Pull request by fsih**
### Resolves

Fix https://github.com/LLK/scratch-gui/issues/1349
Previous PR broke non-text inputs

### CODE REVIEW

**Comment by paulkaplan** [comment]
image

**Comment by fsih** [comment]
I pulled in the change to Input from scratch-paint which accepts className as a prop, and made the width apply only to the sprite name field.

**Comment by amazinigmech2418** [comment]
You should just be able to change the original input selector to `input[type="text"]`...

**Comment by fsih** [comment]
The `input[type="text"]` change caused all of the text inputs to be that wide, which made the sprite info pane too big, like in Paul's screenshot. This change was so it only applies to the sprite name field.

**Comment by amazinigmech2418** [comment]
OK. @fsih

**Pull request merged**
