### PR TITLE
Remove all bitmap assets from libraries

### PR DESCRIPTION
**Pull request by thisandagain**
### Resolves

Resolves GH-913

### Proposed Changes

- Removes all bitmap assets from the sprite, costume, and backdrop libraries. This uses the new `libgen` utility which extracts all assets and builds libraries from a list of Scratch project IDs. In the case of this PR, the project that is being pulled from is `188453716`.

### Reason for Changes

- We would like to remove all bitmap assets until the Bitmap Paint Editor is complete.

### CODE REVIEW

**Comment by thisandagain** [comment]
@ericrosenbaum Yeah. The "legacy" vector sprites all need to be cleaned up. I'm thinking about ideas for how to do this programmatically as manually editing 200+ costumes seems like not much fun.

**Comment by paulkaplan** [comment]
@ericrosenbaum @thisandagain I think the backdrops being off by 100/100 is a new problem that was introduced in this PR? Was that the expected behavior?

Master
image

This
image

**Comment by thisandagain** [comment]
Hmm! Not sure why that would have happened but I'll take a look. I'm guessing we might not be calculating the backdrop rotation center properly in `libgen`.

**Comment by chexbox** [comment]
It looks like re-implementing bitmap sprites may be feasible, soon.

**Pull request merged**
