### PR TITLE
Node 16 upgrade

### LINKED ISSUE #8034: Upgrade CI flow to recent NodeJS
Follow up from https://github.com/LLK/scratch-gui/issues/8000

The tests running on node 10 [https://github.com/LLK/scratch-gui/blob/develop/.circleci/config.yml#L43](https://github.com/LLK/scratch-gui/blob/develop/.circleci/config.yml?rgh-link-date=2022-02-18T22%3A44%3A40Z#L43) which hit EOL last year and security EOL 9 months ago ([endoflife.date/nodejs](https://endoflife.date/nodejs)).

This doesn't impact the deployability of the app since it eventually just runs in the browser but I think it impacts ease of code contribution.

Some factors to consider:

- Developers are more likely to be running a more recent nodejs for other/work projects
- Node 10 isn't available for Apple M1 hardware
- Using a newer nodejs updates package-lock.json, so we probably can't use it for dependency update work. Some dependencies are quite old which I suspect leads to issues like https://github.com/LLK/scratch-gui/issues/5790 lingering for a long time.
- Unit tests (audio-context.test.js specifically) won't pass on node 16, so someone using a newer node can't check the test suite before pushing to CI

By upgrading the CI/deployment flow to use a recent NodeJS we should eliminate most of that friction and we'll have to fix the test compatibility in the process.

Latest passing PR (node 16, chrome 99): https://github.com/LLK/scratch-gui/pull/8120

### PR DESCRIPTION
**Pull request by matschaffer**
### Resolves

- Fixes https://github.com/LLK/scratch-gui/issues/8034
- Based on https://github.com/LLK/scratch-gui/pull/8115

### Proposed Changes

Updates the CI image to node 16

Notable changes from history of https://github.com/LLK/scratch-gui/pull/8115
- https://github.com/LLK/scratch-gui/pull/8120/commits/e3666c519aa1198c3f045a8d14b2432f8ef85464 - helper to allow `AudioContext#resume` in `audio-context.test.js` and `vm-manager-hoc.test.jsx` without unhandled promise rejections

### Reason for Changes

Ease of developer maintenance.

### Test Coverage

N/A

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by kchadha** [comment]
@matschaffer thanks for these changes! Could you rebase this PR against develop after #8146 goes in? 

Could you also break out the web audio test changes into a separate PR since it's separate functionality? If there are any open issues those changes fix please link to those in that new PR as well.

Thanks!

**Comment by kchadha** [comment]
Also before rebasing it might be good to squash some of the commits in this PR for a cleaner history / cleaner rebase.

**Comment by matschaffer** [comment]
Thanks @kchadha, will do!

**Comment by matschaffer** [comment]
@kchadha all done! Let me know if you want any other changes.

**Comment by kchadha** [comment]
> Could you also break out the web audio test changes into a separate PR since it's separate functionality? If there are any open issues those changes fix please link to those in that new PR as well.

Hi @matschaffer it would still be good to make a few separate PRs:
- Update to node 16
- Web audio tests (and explain these changes/why they're necessary in more detail in the PR description)

Also Please leave out the package.json updates as we have other automated systems that handle those and then we don't need to update the package-lock.json in either of these PRs.

**Comment by matschaffer** [comment]
Good idea @kchadha - closing this in favor of https://github.com/LLK/scratch-gui/pull/8159 and https://github.com/LLK/scratch-gui/pull/8160

**Pull request closed without merging**
