### PR TITLE
Stop passing showPreviewInfo to WrappedGui in render-gui

### PR DESCRIPTION
**Pull request by mzgoddard**
### Resolves

Remove the preview modal now that 3.0 has launched. (And load faster)

### Proposed Changes

- Stop passing showPreviewInfo to WrappedGui

### Reason for Changes

The PreviewModal added to load time in a few ways.

- Forces the dom to layout once in all cases
- Forces a second layout if the gui starts fetching the project by id
- Creating and removing DOM thats never shown if fetching the project by id
- (It seems to be correlated but maybe not causing a delay after the first render and presenting that to the screen as the first frame.)

### Browser Coverage / Benchmark Data

Collected while loading a project by id. This measures the duration of the first react render pass.

platform | branch | run 1 | run 2 | run 3 | run 4 | avg
-------- | ------ | ----- | ----- | ----- | ----- | ---
chrome | develop | 743.68 | 716.86 | 773.80 | 710.29 | 736.1575
chrome | no-preview | 700.09 | 715.21 | 631.64 | 656.94 | 675.97
chromebook | develop | 1752.88 | 1564.82 | 1525.09 | 1786.57 | 1657.34
chromebook | no-preview | 1652.79 | 1444.67 | 1513.69 | 1700.21 | 1577.84

### CODE REVIEW

**Comment by paulkaplan** [comment]
You'd need to remove the "try it" step from the integration tests

**Comment by mzgoddard** [comment]
@paulkaplan Thank you. I wasn't sure what was failing.

**Comment by mzgoddard** [comment]
- Remove clickXpath import from test/integration/backpack.test.js

**Comment by mzgoddard** [comment]
@paulkaplan This one line change has a massive impact on tests ... What should we do? Should we turn the preview modal on for tests?

**Comment by paulkaplan** [comment]
@mzgoddard actually another contributor is working on removing the preview modal entirely, so let's just close this in favor of that one https://github.com/LLK/scratch-gui/pull/4410

**Pull request closed without merging**
