### PR TITLE
Make the requiredProjectId work with the online editor

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves https://github.com/LLK/scratch-gui/issues/4072

### Proposed Changes

_Describe what this Pull Request does_

If you aren't on the tutorial project, open it in a new tab in a way that'll work in production

### CODE REVIEW

**Comment by ericrosenbaum** [comment]
hmm, travis is failing in a way that may be legit, on "Load a project by ID directly through url"

**Comment by benjiwheeler** [comment]
LMK if you want me to take a look at the overlap with project-state

**Comment by paulkaplan** [comment]
@ericrosenbaum that is suspicious, although it is running locally for me, so I'm going to rerun it. The code changes were only in the tips library, so although project loading is involved, none of that code should be being touched.

**Comment by paulkaplan** [comment]
@ericrosenbaum confirmed that was a problem with project server, not us. 

I also implemented a confirm to prevent you from leaving a project with unsaved changes.  It isn't great, but I figure anything is better than losing work.

**Pull request merged**
