### PR TITLE
Update .editorconfig and make tabs larger

### PR DESCRIPTION
**Pull request by Time-dragon**
Sorry for not using the template. I was in a hurry.

### CODE REVIEW

**Review by Time-dragon — COMMENTED** [review]
Reviewed by myself.

**Comment by GrahamSH-LLK** [comment]
This should be closed, you didn't even make an issue and get discussion, plus if this change was to be made, it should be by a member of the LLK org.

**Comment by Time-dragon** [comment]
> This should be closed, you didn't even make an issue and get discussion, plus if this change was to be made, it should be by a member of the LLK org.

You are a bully.

**Review by Time-dragon — COMMENTED** [review]
Self review again? Yikes!

**Comment by Time-dragon** [comment]
> This should be closed

No.

> you didn't even make an issue and get discussion

Nobody cares about that.

> if this change was to be made, it should be by a member of the LLK org.

That's nonsense. It's like saying "Fork and commit, then pull here to change the repo!" but actually you fork, commit, and pull, the PR stays there and changes the repo when merged.

**Comment by Time-dragon** [comment]
@GrahamSH-LLK You think I'm wrong?

**Comment by chrisgarrity** [comment]
@Time-dragon sorry this is not in line with the Scratch team policy.

**Comment by Timed-kitty-cat** [comment]
@chrisgarrity "Scratch team policy" is not a thing

**Comment by GrahamSH-LLK** [comment]
> @chrisgarrity "Scratch team policy" is not a thing

I'm not sure if you realize that they're a _member_ of the ST?

**Comment by Timed-kitty-cat** [comment]
> > @chrisgarrity "Scratch team policy" is not a thing
> 
> I'm not sure if you realize that they're a _member_ of the ST?

I realize that dude

**Comment by Timed-kitty-cat** [comment]
> sorry this is not in line with the Scratch team policy.

There is no Scratch team policy.

**Pull request closed without merging**
