### PR TITLE
Remove upload from camera

### PR DESCRIPTION
**Pull request by fsih**
Remove upload from camera from costumes

### CODE REVIEW

**Comment by apple502j** [comment]
Some questions:
- Does this mean moderation policies on pictures changed/will change? [A post in 2020 September by Paddle2See](https://scratch.mit.edu/discuss/post/4385059/) implies that "face reveal" and "posting face" are different, a policy that has been confirmed multiple times ([2019 June](https://scratch.mit.edu/discuss/post/3575038/) and [2017 May](https://scratch.mit.edu/discuss/post/2591863/))
- Is this temporary (for upcoming Scratch Days)?
- Will there be a public announcement, since this is about removing a feature?

**Review by kchadha — APPROVED** [review]
LGTM

**Comment by fsih** [comment]
Please refer to https://scratch.mit.edu/discuss/topic/513228/ for details

**Comment by GrahamSH-LLK** [comment]
That post has a typo:
> While this vision and feature do promote creative expression, a feature which was designed to encourage people to share pictures of themselves does not meet our privacy standards. In response to this, we have removed the feature which created a costume or backdrop from the camera. We're constantly reviewing our features, policies, and resources to ensure that Scratch remains a vibrant community where Scratchers can express themselves creatively in a safe and welcoming environment. This is just one step we're taking in our ongoing privacy and safety efforts.

should be changed like this
```diff
- While this vision and feature do promote creative expression, a feature which was designed to encourage people to share 
+ While this vision and feature does promote creative expression, a feature which was designed to encourage people to share
pictures of themselves does not meet our privacy standards. In response to this, we have removed the feature which created a costume or backdrop from the camera. We're constantly reviewing our features, policies, and resources to ensure that Scratch remains a vibrant community where Scratchers can express themselves creatively in a safe and welcoming environment. This is just one step we're taking in our ongoing privacy and safety efforts.
```

**Pull request merged**
