### PR TITLE
measure blocks text widths with measureText

### PR DESCRIPTION
**Pull request by mzgoddard**
### Resolves

This works in the same area as https://github.com/LLK/scratch-gui/pull/4663. We could choose one or both of these PRs. I think we'll select this one.

### Proposed Changes

Create a set of 2D canvas rendering contexts with their `font` member set to the font used by the text elements for each class. Call measureText and use the returned width value in place of the computed text length from the text element.

### Reason for Changes

After writing some PRs yesterday I recalled another API we can use to measure the text width. [CanvasRendering2DContext.measureText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText), appropriately named, measures some given text according to the font member value. This way we can measure the width of some text on demand without causing DOM style and layout work. The cache is still useful performance wise so we should keep that.

### Browser Coverage

Mac
 * [x] Chrome 
 * [x] Firefox 
 * [x] Safari
  
Chromebook
 * [x] Chrome
 
iPad
* [x] Safari

### Benchmark Data

I'm going to save making this section at the moment. It takes a lot of time to build the data and tables. This should have slightly better to or the same performance as #4663 since it does not need to walk the data before blocks does.

### CODE REVIEW

**Comment by picklesrus** [comment]
My main worry about this PR is overriding ScratchBlocks.getCachedWidth from GUI. Could this PR be made in scratch-blocks instead?  Would we have enough information at Scratch Blocks' inject time to run the text measuring code to build the cache? Feel free to ping me when you're around if you want to chat.

**Comment by mzgoddard** [comment]
- Fix conflicts

**Comment by mzgoddard** [comment]
> Could this PR be made in scratch-blocks instead?

I think so. This code does not explicitly depend on any GUI details. The bit of info the code needs is the font's for the class names scratch-blocks uses. And that is retrieved with computed style that could (and is) used in scratch-blocks.

> Would we have enough information at Scratch Blocks' inject time to run the text measuring code to build the cache?

I'm not sure I understand the question. The text measuring behaviour in scratch-blocks needs the same information to measure text that this version needs. They both need the text to measure and the font decided by css and the given className. If we do not have that information at inject time the current text measurements made by scratch-blocks should be wrong.

> Feel free to ping me when you're around if you want to chat.

I'll ping you tomorrow.

**Comment by picklesrus** [comment]
Closing in favor. https://github.com/LLK/scratch-blocks/pull/1937

**Pull request closed without merging**
