### PR TITLE
Fix Checkbox Row Align

### PR DESCRIPTION
**Pull request by amazinigmech2418**
### Resolves

https://github.com/LLK/scratch-gui/issues/1349

### Proposed Changes

It will fix the align for the checkbox row

### Reason for Changes

It is needed to fix the align as mentioned in the issue.

### Test Coverage

I would do this, but don't know how to get GH pages to build for specifically the amazinigmech2418-develop branch since the other branches include a test Scratch 3 Scratch extension. Also, only the last commit is needed since the other ones were to delete the extension from the branch. @thisandagain I hope this can fix the bug!

### CODE REVIEW

**Comment by amazinigmech2418** [comment]
@thisandagain I hope this helps!

**Comment by amazinigmech2418** [comment]
I figured out .option-card had the text-align set to center and figured that was the problem with the alignment of the checkbox.

**Comment by amazinigmech2418** [comment]
Yes! Travis passed!

**Comment by Kenny2github** [comment]
0.0 that's a lot of commits for a single line change 🤔

**Comment by paulkaplan** [comment]
Sorry this doesn't actually fix the problem. 

image

The issue is that the input has `width: 8rem`, which was introduced by https://github.com/LLK/scratch-gui/pull/1217. I'm going to close this and actually remove help-wanted because @fsih i think you should address this with a fix to that line in `typography.css`.

**Comment by amazinigmech2418** [comment]
@Kenny2github Yeah... I had to delete some stuff from a previous branch to test Scratch 3 extensions... @paulkaplan OK. I didn't see that in the CSS at first.

**Pull request closed without merging**
