### PR TITLE
Implement GH-1074: Add "coming soon" extensions to the library

### PR DESCRIPTION
**Pull request by mewtaylor**
### Resolves

This implements #1074

### Proposed Changes

* Adds a `disabled` state to library items to make them more transparent, make a `Coming Soon` label appear
* Adds 4 new extensions that are disabled
* Changes the library to default to displaying content arranged as `flex-start` rather than `center` (which matches the sprite library)

### Reason for Changes

This is needed for alpha of 3.0

### To-Dos
* Still need an image for the speech extension (/cc @carljbowman)
* May or may not need an icon for wifi, and for active extensions (/cc @carljbowman)

### CODE REVIEW

**Comment by paulkaplan** [comment]
@mewtaylor it looks like you can still click the disabled items and the modal closes. Is that the desired behavior?

**Comment by mewtaylor** [comment]
@paulkaplan whoops! no, not desired – wasn't seeing that locally, but perhaps I didn't test fully! thanks!

**Comment by mewtaylor** [comment]
@paulkaplan blockers – I just edited the labels to denote that!

**Comment by carljbowman** [comment]
@mewtaylor - Thanks for working on this! 

Re todos:
- WiFi Icon (Extension Requirements): We do not need to add those as apart of this work.
- Speech image:  Also added it to the assets in the original issue https://github.com/LLK/scratch-gui/issues/1074#issuecomment-353448320 
speech

**Comment by mewtaylor** [comment]
thanks @carljbowman! @paulkaplan is this good to merge now that the image is updated, you think?

**Comment by paulkaplan** [comment]
👍  Looks good!

**Pull request merged**
