### PR TITLE
Make Sprite/Sound/Costume deletion use the new prompt style

### PR DESCRIPTION
**Pull request by TheBrokenRail**
### Resolves

_Fixes #340 and #385_

### Proposed Changes

_Make Sprite/Sound/Costume deletion use the new prompt style_

### Reason for Changes

_So the prompt styles are consistent_

### Screenshot

asset-delete-new

### CODE REVIEW

**Comment by liam4** [comment]
I think it would be helpful if the dialog also presented what was being deleted:

* Deleting a variable or list should present its name
* Deleting a sprite or costume should should present its name, and a picture of it (lots of people just name their sprites Sprite1, Sprite2, and their costumes costume1, costume2, etc)
* Deleting a sound should present its name, and maybe a "click to play" button like the ones you see in the Sounds tab (again, people might not name their sounds - recording1, recording2, etc aren't useful indicators of what you're deleting!)

**Comment by TheBrokenRail** [comment]
It now shows the sprite/sound/costumes name and image when deleting.

**Comment by rschamp** [comment]
@carljbowman Would you mind dropping in a design for what our modals should look like for these prompts before deleting sprites, sounds and costumes? (Or approve this if it looks ok?)

**Comment by Kenny2github** [comment]
It’s been almost a month since last activity here - any updates?

**Comment by carljbowman** [comment]
@TheBrokenRail - Sorry for the delay. This totally fell off my radar, that's my fault. We appreciate you porting this over to the new modal style, but the delete alerts are temporary for prototyping. Eventually we will remove the alerts entirely.

**Pull request closed without merging**
