### PR TITLE
Revert "adds fastly token to project call"

### PR DESCRIPTION
**Pull request by ghost**
Reverts LLK/scratch-gui#8269

### CODE REVIEW

**Comment by Dhuls-Scratch** [comment]
why?

**Comment by Chiroyce1** [comment]
I'm pretty sure the devs don't merge PRs that don't fix an active issue that requires help - and this also doesn't have much context.

**Comment by picklesrus** [comment]
This PR doesn’t address any issues marked with a priority label so I’m closing it. Please check out our [contributor guidelines](https://github.com/LLK/scratch-gui/blob/develop/.github/CONTRIBUTING.md) to find more details on what kinds of PRs we’re likely to accept.

**Comment by ghost** [comment]
This was an accident lol

**Pull request closed without merging**
