### PR TITLE
Revert render to last good version

### PR DESCRIPTION
**Pull request by fsih**
### Resolves
Fixes https://github.com/LLK/scratch-gui/issues/5105

### CODE REVIEW

**Comment by towerofnix** [comment]
(do see https://github.com/LLK/scratch-svg-renderer/pull/104 before deciding to merge this!)

**Comment by thisandagain** [comment]
Marking as "critical' for hotfix on Monday.

/cc @fsih @paulkaplan @BryceLTaylor

**Comment by paulkaplan** [comment]
@fsih I built this up to a hotfix branch on www so that it is ready to go. We need to also make sure to revert whatever brought this change into scratch-render, so that we do not block future scratch-render updates.

**Comment by paulkaplan** [comment]
@towerofnix we are going to revert it for now to make sure we go back to a known state, then move forward from there to fix t correctly

**Pull request merged**
