### PR TITLE
Add HTTPS clone url in README

### PR DESCRIPTION
**Pull request by epicfaace**
### Resolves

- For consistency's sake in the readme -- issue #4006

### CODE REVIEW

**Comment by Kenny2github** [comment]
Please remember to open an issue and wait for it to be marked "help wanted" before opening a pull to fix it. I don't see [any issue you created](https://github.com/LLK/scratch-gui/issues/created_by/epicfaace) regarding this pull.

**Comment by epicfaace** [comment]
Sure @Kenny2github , I've went ahead and opened an issue -- #4006

**Comment by epicfaace** [comment]
I guess this should be closed now that #4006 has been merged by @rschamp

**Comment by rschamp** [comment]
Right, thanks!

**Pull request closed without merging**
