### PR TITLE
Fix 2911 Part 2

### LINKED ISSUE #2911: Rotation Only Working Every 45 Degrees
### Expected Behavior
Turning 1 degree and moving 1 step constantly should create a circle
### Actual Behavior

It makes an octagon.

### Steps to Reproduce

Create a script where you turn 1 degree and move 1 step constantly.

### Operating System and Browser

Chrome on Windows 10 

It was also reported by henry27q on Scratch.
https://scratch.mit.edu/discuss/topic/299791/?page=277#post-3223192 is where it was reported.

### PR DESCRIPTION
**Pull request by amazinigmech2418**
### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #2911

### Proposed Changes

It rounds in the info panel instead of the position.

### Reason for Changes

Along with the pull request in scratch-vm to revert the position rounding in the setXY function, this will fix the  issue completely and still allow position rounding.

### Test Coverage

I unfortunately cannot build GH pages for the gui.

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

I can't check any, but it's just adding a Math.round() function which is really the basics.

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by Kenny2github** [comment]
17 commits for a ±2-line diff?? Could you do a rebase and squash all of this into one commit, please? Docs on how to do a rebase: https://git-scm.com/docs/git-rebase#_interactive_mode

**Comment by amazinigmech2418** [comment]
@Kenny2github Git doesn't work on my computer... Also, this PR can be just used as a template for a normal commit.

**Comment by Kenny2github** [comment]
It can be squashed and merged, yes, but I strongly advise you actually use git for all but the simplest pull requests. Basically, unless there's only one file to edit, use git.

Also, it looks like a large portion of the commits were for a test extension you made to test out the changes? or is that part of another thing? it looks like it is, since you're pulling from your own develop branch. Here's a handy reminder: make new branches for every pull request, so that you start with a clean base.

**Comment by rschamp** [comment]
@amazinigmech2418 The issue that https://github.com/LLK/scratch-vm/pull/1453 attempted to fix was not the display of the x/y values in the info panel like this PR affects, but the rendered sprite position, so that pen drawing would yield crisp lines.  Thank you for your PR, but please only make PRs that have associated "help wanted" issues in the future.

Also, see https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages for instructions for setting up Travis so that you can publish to gh-pages on your own fork to see the results of your changes if you can't build on your local development environment.

**Pull request closed without merging**
