### PR TITLE
Add 'story' letters to libraries

### PR DESCRIPTION
**Pull request by thisandagain**
### Proposed Changes

- Adds the "story" letters to the sprite and costume libraries
- Re-sync libraries using `libgen`

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [x] Chrome 
 * [x] Firefox 
 * [x] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

/cc @carljbowman @ntlrsk

### CODE REVIEW

**Comment by ntlrsk** [comment]
@carljbowman @thisandagain @ericrosenbaum If you think there are too many letter sprites with Story added back in, perhaps considering dropping the Pixel letter sprites since 1) there will be pixel in the Text editor and 2) Pixel letters seem to be used less often (based on looking at Animate a Name projects posted and in our cards).

**Comment by thisandagain** [comment]
I think we are ok to add these and then re-evaluate once we also have the bitmap assets added to the libraries.

**Comment by thisandagain** [comment]
@ntlrsk Pulling the pixel letters makes sense to me pending landing the new font tool and looking at the data from shared projects over the past 30 days:

### Summary

Group | Projects Shared
-- | --
Block | 86108
Story | 78778
Glow | 65422
Pixel | 22674

### Full
https://docs.google.com/spreadsheets/d/1mqOusuAieMrl88YyKM8mzUdkP74vx4Pu1L2Dddiu6uA/edit?usp=sharing

**Comment by ntlrsk** [comment]
Sounds good. So interesting to see - I'm surprised Story usage tops the Glow letters, even though Story comes last.

**Pull request merged**
