### PR TITLE
"Hide" monitor context menu option

### LINKED ISSUE #4116: Add "Hide" option to monitor context menus
### Expected Behavior

In the context (right-click) menus of monitors (e.g. variables, reporter blocks like "answer", lists) there should be an option called "hide", which hides the monitor.

### Actual Behavior

There is no "hide" option! There isn't even a context menu at all on lists.

### Steps to Reproduce

Show a monitor (e.g. by showing a variable), then right-click on it.

### Operating System and Browser

N/A.

### PR DESCRIPTION
**Pull request by towerofnix**
More or less cherry-picked from #4125.

### Resolves

Resolves #4116.

### Proposed Changes

Adds a new "hide" option to the context menu for monitors. Based off of the code in #4146.

### Reason for Changes

This option is a missing feature from 2.0 and a handy way to quickly get rid of a monitor, especially for inexperienced users who don't realize how they showed the monitor and so aren't sure how to get rid of it.

This PR should merge relatively cleanly with #4146 (e.g. lists should automagically know how to have a "hide" context menu option once that PR is merged).

### Test Coverage

Tested only manually for now. @paulkaplan wrote:

> One last thing is that the context menus for monitors are already covered by some integration tests, so it would be good to add a selenium test for hiding the monitors.

Just to be sure, would this go in `blocks.test.js`?

Edit: I'm not confident I could write any Selenium tests anyhow - when I try to run that test, it reports "SessionNotCreatedError: Chrome version must be >= 69.0.3497.0", but the latest version of Chromium available on Debian testing is 68.0.3440.75. (My `chromedriver` node_modules dependency is also up to date per package.json (2.44.1), if that's relevant.)

### Browser Coverage

Tested on Linux Firefox and Chromium.

### CODE REVIEW

**Comment by towerofnix** [comment]
@IamTregsthedev Thanks for reminding me! It should be able to merge automatically now (once the PR is reviewed).

**Comment by IamTregsthedev** [comment]
No problem. my post

**Comment by benjiwheeler** [comment]
Revisiting this -- it looks like it would make sense for @towerofnix or someone on the Scratch team to add the tests that @paulkaplan suggested.

**Comment by adroitwhiz** [comment]
@towerofnix I've added tests + rebased; mind if I push directly onto your branch?

**Comment by towerofnix** [comment]
@adroitwhiz tyvm!! I've invited you as a collaborator to my fork, which I think should give you permission to push here?

I haven't been doing much work on the Scratch repos lately (I got rid of the gits a couple months ago because they were taking so much space), so the help with finishing up my old PRs is very much appreciated--thank you.

**Comment by adroitwhiz** [comment]
Tests have been added! This can be reviewed now.

**Comment by benjiwheeler** [comment]
@towerofnix I tried this out, and the hide functionality works well.

One problem: the checkmark by the variable in the blocks library doesn't update. I'm wondering if it would be confusing to add this feature without keeping those in sync?

image

**Comment by adroitwhiz** [comment]
@benjiwheeler Checkboxes not updating are fixed by https://github.com/LLK/scratch-gui/pull/4147. Maybe mark this "blocked" instead of "changes requested"?

**Comment by apple502j** [comment]
It's also worth mentioning that previously #4147 and this PR were both included in #4125 and I think they're cherry-pick PR.

**Comment by towerofnix** [comment]
@benjiwheeler Just reiterating adroitwhiz and apple502j's comments: both this pull request and #4147 were (per paulkaplan's request) cherry-picked from the earlier PR #4125. IIRC the code is totally independent of each other, so they can be merged in whichever order (but understandably this one is probably worth merging after the other, since like you said the checkbox not updating in the flyout is a pretty startling side-effect of an existing lack-of-feature fixed by the other PR).

**Comment by benjiwheeler** [comment]
Marking as blocked per merging https://github.com/LLK/scratch-gui/pull/4147 . 

@towerofnix @adroitwhiz I'll try to find out if it's possible to get https://github.com/LLK/scratch-gui/pull/4147 reviewed.

**Review by rschamp — APPROVED** [review]

**Review by seotts — APPROVED** [review]

**Pull request merged**
