### PR TITLE
Filter component + refactored Header from Library Component -> Modal

### PR DESCRIPTION
**Pull request by lifeinchords**
### Resolves

Shell + components for #355 

library filter v3 mov

#### Done
* `LibraryComponent`: moved header logic + css to `ModalComponent`
* `CloseButtonComponent`: large: added similar transition to add button
* `FilterComponent`: added autofocus, made full width

#### Todo:
- [x] Filter: x icon: transitions not working, not sure why
- [ ] Filter: x icon: implement without using CSS selectors with multiple classes?
- [ ] Filter: x icon: transition out
- [ ] Continue on modal, refactor small version used in New Variable
- [x] Center sprite block in library? 
- [ ] Extract X button inside filter form to use `CloseButton`, wire to clear input onClick

This might be useful for wiring to data: https://github.com/enkidevs/react-search-input/blob/master/src/index.js

/cc @paulkaplan @rschamp @carljbowman

### CODE REVIEW

**Comment by paulkaplan** [comment]
Hey sorry about the delay @lifeinchords. Remember when submitting a PR to assign it to someone and assign reviewers so that it shows up in codetree.

**Comment by paulkaplan** [comment]
@lifeinchords this mostly looks good but I think we should include the behavior of the components in this PR to make it a fully self contained change. @rschamp what do you think?

**Comment by lifeinchords** [comment]
Thanks for taking a look @paulkaplan, I thought I assigned and set reviewers, my mistake
Can you share a bit more about `behavior of the components`?

**Comment by paulkaplan** [comment]
Oh as in the actual library filtering when you type.

**Comment by paulkaplan** [comment]
@lifeinchords dd and I extended this branch to include the functionality, and put that into a different PR. https://github.com/LLK/scratch-gui/pull/391

**Pull request closed without merging**
