### PR TITLE
Migrate Videos from YouTube

### PR DESCRIPTION
**Pull request by thisandagain**
## Resolves
Resolves GH-2743

## Changes
This PR migrates tutorial videos away from YouTube and towards a custom solution that we can put behind our CDN moving forward. All videos have been migrated to the new platform and in the case of the "Getting Started" tutorial an initial set of Closed Captions have been loaded.

/cc @SpeakkVisually @ntlrsk @kosiecki

### CODE REVIEW

**Comment by rschamp** [comment]
Try it out: [video](https://llk.github.io/scratch-gui/video)

_I'm a bot, not actually @rschamp!_

**Comment by benjiwheeler** [comment]
This PR may resolve https://github.com/LLK/scratch-gui/issues/2743

Question: @towerofnix on that issue page brought up the possibility of using the `<video>` tag rather than an iframe, so that native players are used. Not sure if that bears on this.

**Comment by thisandagain** [comment]
The native `<video>` tag player does not support all of the features we need.

**Comment by thisandagain** [comment]
@chrisgarrity R?

**Pull request merged**
