### PR TITLE
Sprite library updates

### PR DESCRIPTION
**Pull request by ericrosenbaum**
This is a partial update to the sprite library, pulling in some work by @kosiecki17. it includes updates to about 65 different sprites. These are primarily changes to vector costumes, re-grouping them so they are easier to edit. They also include adding back sprites that had been removed (such as bananas, tablas, congas), adding sounds or new costumes, spelling and capitalization fixes, combining sprites, and other minor edits. There are three totally new sprites (dragonfly, frog 2, and grasshopper).

The changes can be viewed here:
https://llk.github.io/scratch-gui/sprite-library-updates/

Here's a summary of the edits (this may not represent 100% of the changes in the PR):

Andi bounce sound + costumes
Anina 
apple sound
ball sounds
bananas chomp sound
baseball  grouping
basketball bounce sound
bat sound and costumes
batter sound and costume
beach ball bounce sound
bear b alignment of feet
ben-soccer grouping, b-ball sound
bowtie- old deleted
casey- b-ball sound
catcher - new costumes
centaur - snort
Champ99 dance celebrate - new costume
Chick chirp-new costume
crystal -magic spell, collect
Dan- dancer -dance magic
Dani- fashion tag removed new costumes deleted old
devin new costumes
dino1-4 new costumes
donut- chomp-bite
dot-regrouped
dragon-spell
dagonfly-new
dress - changed order of costume
Conga drums - are back!
earth - new and improved
egg- new costumes
led magic spell
empty - removed
fairy - spell
fish - bubbles -ocean wave
fox-costumes
frank -sounds and grouping
Frog 2 -new sprite-wetlands
fruit salad-chomp
ghost -space ripple, grouping
giga- editied costume removed
giraffe, gallop, grouping
glass of water -caps
glasses- clothing tag
goalie- grouping, sound
goblin
devin  
goalie, sound, costumes
grasshopper - new
green flag
griffin - removed griffin flying
Guitar Sounds - caps
Elec Guitar -sounds capped
elec guitar 2 - sounds capped
Hare new costumes
Harper -reordered
hat -renamed
Hatchling egg
Hat beanie removed
heart - candy, new costumes
hen resized, new sound
horse -new sounds
jellyfish sound
jordyn, regrouped

### CODE REVIEW

**Comment by rschamp** [comment]
Try it out: [sprite-library-updates](https://llk.github.io/scratch-gui/sprite-library-updates)

_I'm a bot, not actually @rschamp!_

**Comment by apple502j** [comment]
What's the dot? 
image

**Comment by towerofnix** [comment]
@apple502j That's a fly - the costume "Frog 2-b" shows the frog grabbing it with its tongue (and "Frog 2-c" shows it leaping at the fly).

**Comment by ericrosenbaum** [comment]
I'm going to close this and make one for the full update instead

**Pull request closed without merging**
