### PR TITLE
Add size and remove rotation style from sprite info area.

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-gui/issues/1064

size-setter

### CODE REVIEW

**Comment by fsih** [comment]
Should the field be a bit bigger? It starts showing '...' around 200% which is pretty small

**Comment by paulkaplan** [comment]
@fsih I agree, @carljbowman should just that field be larger, or each of the bottom inputs (direction & size)?

**Comment by thisandagain** [comment]
Agreed. My inclination would be to slightly increase the width of both the direction and size fields.

**Comment by paulkaplan** [comment]
Simpler solution was to take down the padding (it is center aligned anyway) for the smaller inputs, and remove the ellipses (since they take up 50% of the input). 

image

**Pull request merged**
