### PR TITLE
Update toolbox before ScratchBlocks inject and Give  IDs to some shadow blocks

### PR DESCRIPTION
**Pull request by Micircle**
### Reason for Changes

1.Toolbox should be updated before ScratchBlocks inject to avoid repeated rendering.
2.Some monitored blocks's shadow blocks also need IDs.

### CODE REVIEW

**Comment by paulkaplan** [comment]
@rschamp any idea why this isn't building on travis?

**Comment by paulkaplan** [comment]
@Micircle Sorry about the delay on this, trying to figure out with travis why this isn't building. I'm going to run the tests locally and then it should be good to merge.

**Comment by paulkaplan** [comment]
@Micircle it looks like linting is failing on blocks.jsx line 56
```
error    Line 56 exceeds the maximum line length of 120
```
Could you split that line up and then we can merge this.

**Comment by Micircle** [comment]
I'm sorry about this. I will run tests next time.

**Pull request merged**
