### PR TITLE
Add shrink/expand and new fencing feature to tutorial cards

### LINKED ISSUE #4667: Update Tutorial Window Fencing
## Current
The tutorial window is "fenced" in such a way that no part of the tutorial window can be outside the browser. 

current fencing

## Update
We'd like to allow the tutorial window to be able to go beyond the edge of the browser. We want to make it so it's easier to move the window out of the way and make space for interacting with other parts of the editor. 

- The tutorial window should be able to extend beyond the browser's left/right edge by 80% the windows width. 
- The tutorial window should be able to extend beyond the browser's bottom(/top) edge by 80% the windows height. My instinct tells me allowing the window to exit the top of the browser might feel weird — more in the questions below.  

We can revalue how that feels once prototyped.

### Fencing Left Example
V2 - Getting Started - Fencing Left

### Fencing Bottom Example
V2 - Getting Started - Fencing Bottom

### Questions
- Do we need a way to reset the window to the default position?
- Should the window stay the last place it was put when opening a new tutorial?
- Should we allow the window to exit the top of the browser? This would break conventions with similar drag-and-drop window UI. Might be worth prototyping with and without.

### LINKED ISSUE #4670: Add Shrink/Expand Feature to Tutorial Window
## Overview
We'd like to include a way to shrink (aka collapse) the tutorial window. Shrinking the UI will easier to interact with other parts of the editor and hopefully will decrease people closing the tutorial window, which has the additional side effect of losing your place in the tutorial. 

[Invision Mock / Prototype](https://projects.invisionapp.com/d/main#/projects/prototypes/16823838)

#### Tutorial Expanded View (Default view)
- A new toggle button gets added to tutorial window nav. Icon is pending.
- All buttons take on new style with icon and text stack. 

video step

#### Tutorial Collapsed View
- The collapsed view should still be draggable
- The position in tutorial steps should be retained when collapsing. If someone is on Step 3 and collapses  the window, they should remain on Step 3 when they re-expand the window
- If there is a video, the playhead should be retained when collapsed

collapsed view

#### Dependancies
- The fencing work will have some implications on this work. 
  - We may need to play with causing some sort of reset if a window is off beyond the edge of the browser and then is expanded / collapsed.
  - If a window is collapsed we may want to limit the amount that it can exit off the top or bottom of the browser.

### LINKED ISSUE #4765: Tutorials should always open in expanded mode
When using the shrink/expand button on the tutorial window, the state should always reset to expanded mode when you open a tutorial using the tutorial library.

### PR DESCRIPTION
**Pull request by evhan55**
### Resolves

- Resolves #4670: Add Shrink/Expand Feature to Tutorial Window
- Resolves #4667: Update Tutorial Window Fencing
- Resolves #4765: Tutorials should always open in expanded mode
- Tutorials should always activate at the starting position

### Proposed Changes

Add a new card header button to shrink/expand the tutorial cards.  Also add a new fencing mechanism to be able to drag cards slightly out of bounds.

### Reason for Changes

So tutorials are discarded less often.

### CODE REVIEW

**Comment by evhan55** [comment]
@carljbowman @ericrosenbaum 

I am starting to work on this feature.  I have gotten some of the React plumbing hooked up and I am beginning to test initial functionality without icons, using 'Shrink' / 'Expand' labels instead for now.  Basic toggling is working, but the header shrinks to size without a video/image in the card body.  Any idea what you'd like it to do?  Should I set a `min-width` somehow for the header?


Screen Shot 2019-04-10 at 1 43 28 PM

Screen Shot 2019-04-10 at 1 43 34 PM

**Comment by carljbowman** [comment]
@evhan55 - Thanks for the update! 

Re icons:
I'll get sketching on some "Shrink" and "Expand" icons. Thanks for the reminder on that.

Re min-width: 
My initial thought would be to make the min-width the same size as the step's width, in other words the bar should not shrink horizontally, but only step content should only collapse vertically.  
@ericrosenbaum - This may have implications on how things will become fenced, as we plan to use the tutorial's width and height to determine how far it can "exit" beyond the browser window.

**Comment by evhan55** [comment]
Hi @carljbowman, @ericrosenbaum and I looked at the progress on this PR today and have a question for you: for the new button layout of label/text stacking, it seems like possibly the text size and icon size have to shrink in order for the new header to retain the same height as the old header, does that sound right to you?  Let me know how you'd like me to play with text size, icon size and margins and if the new header wants to stay the same height, or not.

older header right now:
Screen Shot 2019-04-15 at 2 32 58 PM

new header with minimal changes:
Screen Shot 2019-04-15 at 2 33 05 PM

**Comment by evhan55** [comment]
@carljbowman @ericrosenbaum 

Current progress on this feature see GIF below.  I think it's pretty close now, so I will move onto the fencing feature.  I will mark this 'needs review' now but it won't be able to merge until the fencing feature is done/reviewed as well.

shrink-expand

**Comment by evhan55** [comment]
Here is the current fencing proposal:

drag cards 2

**Comment by evhan55** [comment]
@ericrosenbaum Thank you very much for catching that!  I have tried a new horizontal positioning, changing the value that was there before, let me know if it looks ok to you!

**Pull request merged**
