### PR TITLE
Updates to preview modal for release

### PR DESCRIPTION
**Pull request by thisandagain**
### Proposed Changes
- Remove "Open in 3.0" button (redundant with button added to project page)
- Add disclaimer regarding saving of Scratch projects

image

### CODE REVIEW

**Comment by thisandagain** [comment]
@rschamp I was curious about that too. Happy to remove.

**Comment by thisandagain** [comment]
Some revisions plus removal of the "load a 2.0 project" component.

image

**Comment by thisandagain** [comment]
More edits:
image

**Comment by thisandagain** [comment]
Note to self: squash when merging this.

**Comment by thisandagain** [comment]
@paulkaplan and/or @rschamp Could you folks give this one more look?

**Comment by thisandagain** [comment]
@paulkaplan I agree that more concise language would be ideal. My worry with that specific suggestion is that it doesn't communicate that you eventually *will* be able to save to the community. The number one question / comment we get right now from the community is worry about if accounts and projects will be transferred over to 3.0.

**Comment by thisandagain** [comment]
@paulkaplan How would you feel about the following as a compromise? This revision is an attempt to avoid "burying the lead" and avoid redundancy while still being clear / accurate.

> Changes to Scratch projects will not be saved to the Scratch community. This feature is coming soon!

**Comment by thisandagain** [comment]
Yay. Thanks for all the feedback @kchadha @paulkaplan @carljbowman and @ericrosenbaum. I'm feeling pretty good about this:

image

**Comment by kchadha** [comment]
@thisandagain Last nit, new line before the second sentence?

**Pull request merged**
