### PR TITLE
Fixed issue causing right click to drag sprite. 

### PR DESCRIPTION
**Pull request by bartljak**
### Resolves

Issue 701 (https://github.com/LLK/scratch-gui/issues/701)

### Proposed Changes

I have added an if statement to check what click is being used when clicking on the sprite. If it is a right click, the sprite is unable to be dragged.

### Reason for Changes

Before this change the user could right click the sprite, and then left click on the stage and the sprite would be dragged to where you left clicked, causing unexpected behavior.

### Test Coverage

All npm test test cases passed, this is a very small change so I did not see additional tests necessary.

### CODE REVIEW

**Comment by bartljak** [comment]
Sorry about the double pull request, I had some issues with branching.

**Comment by VutonDesign** [comment]
@bartljak You'll probably need to edit this,the travis-ci build found some errors.

**Comment by bartljak** [comment]
@VutonDesign Yeah I am working on that now, I'm not sure why npm test is passing all tests locally on my machine but is failing for travis-ci.

**Comment by VutonDesign** [comment]
@bartljak Right, Good luck then! 👍

**Comment by Kenny2github** [comment]
@bartljak why'd you close this again?

**Comment by bartljak** [comment]
@Kenny2github Sorry I thought I was supposed to close the pull request until it passed all of the checks, I am still trying to fix errors with this change. I will reopen it now.

**Comment by bartljak** [comment]
I am now checking for a right click instead of a left click. All travis test cases are passing!

**Comment by paulkaplan** [comment]
Hi @bartljak, thanks for the submission! Poking around the MDN documentation, it looks like `event.which` is not part of the standard anymore and we should use `event.button` instead? I think you should be safe checking if `event.button === 0`.

**Comment by bartljak** [comment]
@paulkaplan Sorry about that! I have made the appropriate changes.

**Comment by paulkaplan** [comment]
Great! LG. I'll merge this now.

**Pull request merged**
