### PR TITLE
Solved #98 scrollbar in SpriteSelector not showing up

### LINKED ISSUE #98: [Safari] Overflow scroll not working in SpriteSelector pane
### Expected Behavior

Person should be able to scroll the pane

### Actual Behavior

No scrollbar is present, can't scroll.

### Steps to Reproduce

Load a project with more items than visible in one page-full.

### Operating System and Browser

Safari 10.0.1 (12602.2.14.0.7)

screen shot 2017-02-15 at 8 59 06 am

### PR DESCRIPTION
**Pull request by bigeyex**
### Resolves

#98

### Proposed Changes

Use flexbox in every element in the right panel.

This is because mixing flexbox and box layout have compatibility issues across browsers,
and may result in unexpected behavior. This is discussed in this article:

http://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

### CODE REVIEW

**Comment by lifeinchords** [comment]
Thanks for submitting this @bigeyex. I didn't realize mixing could cause issues and this explains a lot of the trouble I ran into refactoring the layout across browsers. This also has a bonus of fixing #105 .

This fix works in Sierra + Safari (Version 10.0.1 (12602.2.14.0.7)). 
On my machine, Sierra + latest Firefox (45.2.0) the `spriteSelector` pane doesn't scroll. 

@rschamp, could you check this out and see if Firefox is also breaking?

**Comment by lifeinchords** [comment]
whoops, didn't see @paulkaplan assigned, can you give it a shot?

**Comment by paulkaplan** [comment]
@lifeinchords hey sorry i'm pretty backed up I'll get back to you on this shortly.

**Comment by paulkaplan** [comment]
@lifeinchords can you use browserstack to try this on a range of things? I know we have a few different issues related to safari and other browsers, not sure if we want to invest in browser support at this stage.

**Comment by paulkaplan** [comment]
@bigeyex looks like this doesn't work in current Firefox.

**Pull request closed without merging**
