### PR TITLE
Confine add buttons to stage and sprite selectors

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-gui/issues/86

### Proposed Changes

_Describe what this Pull Request does_

Restructures the layout to force the add sprite and add backdrop buttons to be within their respective panels. 

### Test Coverage

_Please show how you have added tests to cover your changes_

This is exactly the type of change that end-to-end testing will be able to automatically make sure doesn't break anything! until then, manually.

### CODE REVIEW

**Comment by paulkaplan** [comment]
@rschamp what should we do with the vertical constraint?

**Comment by rschamp** [comment]
Confine them to these areas? @carljbowman?

image

**Comment by paulkaplan** [comment]
I'm just not sure that is an issue. I think our minimum resolution is basically ipad (1024x768), anything smaller than that I'm not sure it is worth considering

**Comment by paulkaplan** [comment]
@rschamp In order to properly address that, we would need to make a min-height for the whole UI and make it possible to scroll. I'd rather deal with that part separately.

**Pull request merged**
