### PR TITLE
fix: uepr-38: update debug modal image

### PR DESCRIPTION
**Pull request by KManolov3**
### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #

### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Review by MiroslavDionisiev — APPROVED** [review]

**Comment by KManolov3** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by KManolov3** [comment]
recheck

**Comment by KManolov3** [comment]
recheck

**Comment by KManolov3** [comment]
recheck

**Pull request merged**
