### PR TITLE
Fix language selector alignment

### PR DESCRIPTION
**Pull request by chrisgarrity**
### Resolves

- Resolves ##3301 

### Proposed Changes

* Adjust language icon and caret in menu-bar
  * add slight margin on left and and right (works for both LTR and RTL languages)
* remove unused style from `language-selector.css`

### Reason for Changes

Align language icon with Scratch logo and tutorials icon

### Test Coverage

Current tests run

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [x] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by chrisgarrity** [comment]
Tests are going to fail due to https://github.com/LLK/scratch-gui/pull/3305

**Comment by benjiwheeler** [comment]
Only problem is that the width of `$language-selector-width` in `units.css` is currently 3rem, which makes the total width look like:

screen shot 2018-10-05 at 2 34 08 pm

...if we bump this up to 3.5rem, it looks much neater:
screen shot 2018-10-05 at 2 37 52 pm

...alternatively, if we decrease the language-icon height from 1.5rem to 1.25rem, it also looks better, and the icon size seems (to me) more in line with the other menu icons:
screen shot 2018-10-05 at 2 43 23 pm

**Comment by chrisgarrity** [comment]
I'm concerned that we already lose most of the title in some languages on smaller screens - it doesn't seem worth adding more width to the language icon - it already has a lot of space around it. How about reducing the padding instead (using .5rem instead of .75rem):
screen shot 2018-10-09 at 8 25 30 am

Spacing without highlight:
screen shot 2018-10-09 at 8 26 46 am

@carljbowman what do you think? reduce the padding, reduce the icon size, or increase the width?

**Comment by chrisgarrity** [comment]
@benjiwheeler I've updated the css for the language-selector. I spoke with @carljbowman and he thought reducing the padding for the language selector was fine.

**Comment by chrisgarrity** [comment]
BTW, you can try it here: https://chrisgarrity.github.io/scratch-gui/issue/2658-lang-select/
(once travis finishes building)

**Comment by benjiwheeler** [comment]
OK, LGTM. FYI, this is what it looks like now on my mac chrome:

screen shot 2018-10-11 at 10 45 13 pm

**Comment by benjiwheeler** [comment]
Emptied cache and hard reloaded, seems the same. (I'm not sure you create those build branches, or if they're created automatically? Should I pull the PR instead?)

screen shot 2018-10-12 at 8 45 38 am

**Comment by benjiwheeler** [comment]
Downloaded the diff and tried it locally, looks great! The built branch was just stale.

screen shot 2018-10-12 at 9 59 27 am

**Pull request merged**
