### PR TITLE
ENA-118 Replace text-encoding polyfill with much smaller library, saving 500KB

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

- Towards #6898

### Proposed Changes

This PR replaces the `text-encoding` package with `fastestsmallesttextencoderdecoder`.

### Reason for Changes

The `text-encoding` package has been deprecated by its maintainer, and also adds 500KB of encoding data for non-UTF-8 text. Because we're only using it to encode UTF-8, that 500KB is entirely unnecessary.

### Test Coverage

Must be tested manually.

Here, the `TextEncoder` API is used to encode assets for the default project. To test this, create a new default project in Legacy Edge, the only browser without native `TextEncoder` support.

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge

Linux
 * [x] Firefox
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by adroitwhiz** [comment]
Test failures seem to be the result of a ChromeDriver version mismatch

**Comment by benjiwheeler** [comment]
To be super clear, this way of providing encoding functions is _only_ needed on legacy Edge, right? Does that include basically all known pre-chromium versions of Edge?

**Comment by benjiwheeler** [comment]
Added "accessibility" label because reducing download size (for both app and website) is meaningful for improving access when data is slow or expensive

**Comment by apple502j** [comment]
@benjiwheeler Yep, this library is used by all Legacy (non-Chromium) Edge - and by ONLY the Legacy Edge (at least for supported environments).

**Comment by adroitwhiz** [comment]
Just a reminder that in order to actually remove this huge dependency from the *bundle*, you'll need to remove it from [all the other packages too](https://github.com/LLK/scratch-gui/issues/6898).

**Review by cwillisf — APPROVED** [review]

**Comment by adroitwhiz** [comment]
@cwillisf Since this PR was first opened, I came across https://www.npmjs.com/package/fast-text-encoding, which seems to be far more popular and faster. I can create another PR for that if you want.

You could also consider dropping the polyfill entirely--the only browser which does not support `TextEncoder` and `TextDecoder` is Edge Legacy, which [has reached EOS and doesn't even seem to be installable anymore](https://learn.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details).

**Comment by cwillisf** [comment]
Yeah - I think removing it entirely is the right answer. Honestly, I merged this because it's relatively self-contained, and wanted to send a signal that I'm trying to make at least some small amount of progress :sweat_smile:

**Pull request merged**
